### ISSUE TITLE
Perks out of order in skills menu

### ISSUE THREAD

**Issue by SFMason** [Sirillion/SMXui#3]
In the skills menu, The Electrocutioner perk is in the slot for From the Shadows, all Intelligence perks are shifted left to fill the hole left by Electrocutioner, and the From the Shadows perk is moved to the final slot (after Yeah Science). 
![smxui-skills-menu-bug](https://user-images.githubusercontent.com/42695951/71672261-78257180-2d43-11ea-9a4c-ab8e214d86df.jpg)

I tried commenting out the grid entry for perkFromTheShadows in Config/XUi/windows.xml (line 1663-1665), and it fixed the shifting issue (except of course the From the Shadows perk is no longer accessible).
![from-the-shadows-removed](https://user-images.githubusercontent.com/42695951/71672370-b6229580-2d43-11ea-8e2a-114a2c9bbfb1.jpg)

I then put From the Shadows back and commented out perkElectrocutioner (lines 1673-1675), and From the Shadows is replaced by Electrocutioner, while the proper spot for Electrocutioner is empty.
![electrocutioner-removed](https://user-images.githubusercontent.com/42695951/71672492-17e2ff80-2d44-11ea-9fa6-a434aa778633.jpg)

**Comment by Sirillion** [comment]
Not able to reproduce on my end. All looks to be where it should here. Are you sure you are not running another mod that also modify the progression file?

**Comment by SFMason** [comment]
Looks like it is another mod that adds an effect to rank 5 of From the Shadows:
[Night Vision Modlet](https://www.nexusmods.com/7daystodie/mods/636)

Specifically, in that mod's Config/progression.xml:
`<remove xpath="/progression/perks/perk[@name='perkFromTheShadows']" />

<append xpath="/progression/perks">

	<perk name="perkFromTheShadows" parent="skillStealth" name_key="perkFromTheShadowsName" desc_key="perkFromTheShadowsDesc" icon="ui_game_symbol_bat">
		<level_requirements level="1"><requirement name="ProgressionLevel" progression_name="attAgility" operation="GTE" value="1" desc_key="reqAgilityLevel01"/></level_requirements>
		<level_requirements level="2"><requirement name="ProgressionLevel" progression_name="attAgility" operation="GTE" value="3" desc_key="reqAgilityLevel03"/></level_requirements>
		<level_requirements level="3"><requirement name="ProgressionLevel" progression_name="attAgility" operation="GTE" value="5" desc_key="reqAgilityLevel05"/></level_requirements>
		<level_requirements level="4"><requirement name="ProgressionLevel" progression_name="attAgility" operation="GTE" value="7" desc_key="reqAgilityLevel07"/></level_requirements>
		<level_requirements level="5"><requirement name="ProgressionLevel" progression_name="attAgility" operation="GTE" value="10" desc_key="reqAgilityLevel10"/></level_requirements>
		<effect_group>
			<requirement name="CVarCompare" cvar="_crouching" operation="Equals" value="1"/>
			<passive_effect name="LightMultiplier" operation="perc_add" level="0,5" value="0,-.65">
				<requirement name="CVarCompare" cvar="_lightlevel" operation="LTE" value="50"/>
			</passive_effect>
			<passive_effect name="NoiseMultiplier" operation="perc_add" level="0,5" value="0,-.5"/>
			<passive_effect name="CrouchSpeed" operation="perc_add" level="0,5" value="0,0.5"/>

			<effect_description level="1" desc_key="perkFromTheShadowsRank1Desc" long_desc_key="perkFromTheShadowsRank1LongDesc"/>
			<effect_description level="2" desc_key="perkFromTheShadowsRank2Desc" long_desc_key="perkFromTheShadowsRank2LongDesc"/>
			<effect_description level="3" desc_key="perkFromTheShadowsRank3Desc" long_desc_key="perkFromTheShadowsRank3LongDesc"/>
			<effect_description level="4" desc_key="perkFromTheShadowsRank4Desc" long_desc_key="perkFromTheShadowsRank4LongDesc"/>
			
			<effect_description level="5" desc_key="perkFromTheShadowsRank5Desc" long_desc_key="Hide in the shadows 65% more effectively, noises from actions are muffled 50% and sneak movement is 50% faster. And you can now craft a nightvision mod"/>
			<passive_effect name="RecipeTagUnlocked" operation="base_set" value="1" level="5" tags="modNightvision"/>
			
		</effect_group>
	</perk>

</append>`

So it looks like it might be deleting your From the Shadows perk and appending its own. Is there a way to fix this short of pasting that mod's source code into yours?

**Comment by Sirillion** [comment]
Downloaded and checked the files now.

The problem is that he removes and then re-injects the perk instead of an easy set and insertafter. For vanilla this is not an issue as it is last on the agility attribute if I am not mistaken, so if it shifts position in the progression.xml file it is not a big deal. But for SMX it is and to make the one panel look that SMX has it requires the perks to load in order in the file, deleting and as such moving the position of one will yield these results.

I would simply rewrite his mod if you're xpath savvy, and he should also do that to increase compatibility with other mods. His function would remain the same but his modlet would be WAY easier to maintain.
`
<set xpath="/progression/perk[@name='perkFromTheShadows']/effect_group/effect_description[@level='5']/@long_desc_key">Hide in the shadows 65% more effectively, noises from actions are muffled 50% and sneak movement is 50% faster. And you can now craft a nightvision mod</set>
`
and
`
<insertAfter xpath="/progression/perk[@name='perkFromTheShadows']/effect_group/effect_description[@level='5']">
<passive_effect name="RecipeTagUnlocked" operation="base_set" value="1" level="5" tags="modNightvision" />
</insertAfter>
`
Would be all that would be needed to fix that issue I think, I haven't tested the code, just typed it out here but that should inject to the correct place and yield the same result without moving the perk position in the file.

**Comment by SFMason** [comment]
Nice. Commented out the remove/append and pasted your code, worked perfectly. I'll see if I can contact him with this fix.

Btw keep up the good work. Your menus were how this game was supposed to look.
